import Foundation

// App language is independent of the macOS language.
@MainActor func L(_ russian: String) -> String {
    guard Settings.shared.language != "ru" else { return russian }
    if let translated = englishStrings[russian] { return translated }
    let prefix = "Не удалось прочитать: "
    if russian.hasPrefix(prefix) { return "Could not read: " + russian.dropFirst(prefix.count) }
    return russian
}

private let englishStrings: [String: String] = [
    "Показывать в строке меню": "Show in Menu Bar",
    "Показывать в Dock": "Show in Dock",
    "Если обе иконки скрыты, откройте Dropzone из папки «Программы», чтобы вернуться в настройки.": "If both icons are hidden, open Dropzone from Applications to return to Settings.",
    "Поддержать донатом": "Donate",
    "Репозиторий GitHub": "GitHub Repository",
    " · без содержимого папок": " · excluding folder contents",
    " — изменить": " — Edit",
    ". Оригиналы файлов останутся на месте.": ". Your original files will stay in place.",
    "1. Возьмите файл и встряхните курсор.\n2. Положите его на полку.\n3. Переключитесь в нужное окно и заберите файл.": "1. Pick up a file and shake the pointer.\n2. Drop it onto the shelf.\n3. Switch to your destination and drag it out.",
    "Dropzone — нажмите или перетащите файлы": "Dropzone — click or drop files",
    "Dropzone — настройки": "Dropzone — Settings",
    "Dropzone — полка": "Dropzone — Shelf",
    "Активация": "Activation",
    "Быстрый просмотр": "Quick Look",
    "Быстрый старт": "Quick Start",
    "Все файлы остаются на вашем Mac": "Your Files Stay on Your Mac",
    "Встряхните курсор, удерживая файлы из Finder.": "Shake the pointer while dragging files from Finder.",
    "Встряхните файл · положите · заберите": "Shake · drop · drag out",
    "Всё под рукой — в удобном ритме.": "Keep your files close at hand.",
    "Вызов встряхиванием": "Activate with Shake",
    "Высокая": "High",
    "Глобальная горячая клавиша": "Global Keyboard Shortcut",
    "Действия с файлами": "File Actions",
    "Добавьте ⌘, ⌥ или ⌃": "Include ⌘, ⌥ or ⌃",
    "Если элементов больше ": "When item count exceeds ",
    "Завершить Dropzone": "Quit Dropzone",
    "Закрыть и очистить": "Close and Clear",
    "Закрыть и очистить полку": "Close and Clear Shelf",
    "Закрыть полку и очистить содержимое?": "Close and clear the shelf?",
    "Запускать при входе": "Launch at Login",
    "Клавиша ": "Key ",
    "Крестик и ⌘W закрывают полку и очищают её. При превышении порога появится вопрос. Оригиналы файлов сохраняются.": "× and ⌘W close and clear the shelf. Above this limit, you will be asked to confirm. Original files are kept.",
    "Мягкое свечение при приближении. Синяя обводка — можно отпускать файл. Доступно на дисплее с вырезом камеры.": "A soft glow as you approach. A blue outline means you can drop. Available on displays with a camera notch.",
    "На полке элементов: ": "Items on the shelf: ",
    "Нажмите сочетание · Esc для отмены": "Press a shortcut · Esc to cancel",
    "Настройки…": "Settings…",
    "Нативно. Локально. Без ожидания.": "Native. Local. No waiting.",
    "Не удалось прочитать: ": "Could not read: ",
    "Недоступен": "Unavailable",
    "Некоторые файлы недоступны. Проверьте оригиналы в Finder.": "Some files are unavailable. Check the originals in Finder.",
    "Нет аналитики, аккаунтов и загрузок в облако. Полка работает без интернета.": "No analytics, accounts, or cloud uploads. The shelf works offline.",
    "Низкая": "Low",
    "Оригиналы остаются на месте": "Original Files Stay in Place",
    "Основные": "General",
    "Оставлять открытой после передачи": "Keep Open After Dragging Out",
    "Открыть": "Open",
    "Открыть список файлов": "Open File List",
    "Отмена": "Cancel",
    "Отпустите файлы": "Drop Files",
    "Оформление": "Appearance",
    "Очистить полку": "Clear Shelf",
    "Папка": "Folder",
    "Перетаскивание на монобровь": "Drop to Notch",
    "Перетаскивание наружу копирует файлы. Очистка полки удаляет только ссылки. Содержимое временное и не восстанавливается после выхода из приложения.": "Dragging out copies files. Clearing removes only references. The shelf is temporary and is not restored after quitting.",
    "Перетащите сюда": "Drop Files Here",
    "Перетащить все файлы": "Drag All Files",
    "Поведение полки": "Shelf Behavior",
    "Подтвердите запуск в Системных настройках → Основные → Объекты входа.": "Allow launch in System Settings → General → Login Items.",
    "Подтверждать закрытие": "Confirm Before Closing",
    "Показать / скрыть полку": "Show / Hide Shelf",
    "Показать в Finder": "Reveal in Finder",
    "Показать полку": "Show Shelf",
    "Показать сетку": "Show Grid",
    "Показать список": "Show List",
    "Полка плавно держится сбоку. При приближении к ней и работе с файлами движение останавливается. Переключатель также есть на самой полке.": "The shelf follows beside your pointer and pauses when you get close or interact with files. You can also toggle this on the shelf.",
    "Полка появляется, когда нужна.": "Your shelf, when you need it.",
    "При выключении полка скрывается после успешного переноса. Перенесённые элементы удаляются с полки; отменённые остаются.": "When off, the shelf hides after a successful drop. Transferred items leave the shelf; cancelled items remain.",
    "Применяется сразу.": "Changes take effect immediately.",
    "Пробел": "Space",
    "Пробел — Quick Look · ⌘A — выбрать всё\nDelete — убрать с полки · ⌘F — следование\n⌘, — настройки (при активной полке, любая раскладка)": "Space — Quick Look · ⌘A — Select All\nDelete — Remove from Shelf · ⌘F — Follow\n⌘, — Settings (when focused, in any layout)",
    "Свернуть": "Collapse",
    "Светлое": "Light",
    "Системное": "System",
    "Следование включено — выключить": "Follow is On — Turn Off",
    "Следование выключено — включить": "Follow is Off — Turn On",
    "Следовать за курсором": "Follow Pointer",
    "Сочетание занято или недоступно. Выберите другое.": "This shortcut is unavailable or in use. Choose another.",
    "Средняя": "Medium",
    "Тёмное": "Dark",
    "Убрать с полки": "Remove from Shelf",
    "Чувствительность": "Sensitivity",
    "Язык": "Language",
    "Добро пожаловать в Dropzone": "Welcome to Dropzone",
    "Временная полка для файлов, которая всегда рядом.": "A temporary file shelf that stays close at hand.",
    "Встряхните": "Shake",
    "Удерживая файл, встряхните курсор — полка появится рядом.": "Shake the pointer while holding a file to summon the shelf.",
    "Положите": "Drop",
    "Перетащите файл на полку или к вырезу камеры MacBook.": "Drop a file onto the shelf or your MacBook camera notch.",
    "Заберите": "Drag Out",
    "Переключитесь в нужное приложение и перетащите файл с полки.": "Switch to your destination and drag the file out of the shelf.",
    "Локально и приватно": "Local and Private",
    "Dropzone не загружает файлы в облако и не собирает аналитику. Оригиналы остаются на месте.": "Dropzone does not upload files or collect analytics. Originals stay where they are.",
    "Начать работу": "Get Started",
]
